### ISSUE TITLE
Idea for a new option: --include

### ISSUE THREAD

**Issue by hoelzro** [beyondgrep/ack2#136]
The proposed `--include` option would include another ackrc file into the current one.  The reason I want a feature like this is that I manage my dotfiles (such as my user ackrc) in a Git repo, and I'd like to be able to apply machine-specific settings without worrying about my site-specific stuff being blown away.  So my ideal ackrc would look something like this:

```
--type-add=perl6:ext:p6,pm,pm6
--include=~/.ackrc.local
```

**Comment by petdance** [comment]
@hoelzro Do you still think this is a worthwhile feature?

**Comment by petdance** [comment]
There will probably be no more releases of ack 2.  If this is still a relevant idea, please submit it to the ack3 repo.
