### ISSUE TITLE
Add parallelism to ack

### ISSUE THREAD

**Issue by hoelzro** [beyondgrep/ack2#152]
Brought up [here](https://groups.google.com/forum/?fromgroups=#!topic/ack-users/5ao9j2cB3CY).

One possible way to optimize ack (especially when files are in the FS cache or potentially on SSDs) would be to create a parallel version.

**Comment by petdance** [comment]
There will probably be no more releases of ack 2.  If this is still a relevant idea, please submit it to the ack3 repo.
