### ISSUE TITLE
Catch beginner mistakes with warnings

### ISSUE THREAD

**Issue by hoelzro** [beyondgrep/ack2#200]
## Detect when file selectors aren't used

When an explicit target list of only files is used, file selectors such as `--type=perl`, `--ruby`, or `--ignore-dir=blib` are not consulted.  For example:

```
ack foo --ruby file.pl
```

The `--ruby` is valid, but because `file.pl` is specified on the command, it is not type-checked.  To the user's eyes, the `--ruby` is broken because ack still searched Perl file.
## Detect when a normally ignored directory is specified on the command line

In the case of this invocation:

```
ack foo --perl foo.pl blib/
```

`blib/` will be searched, because it is specified on the command line.  However, a warning stating that "blib is normally ignored, but will be searched anyway" would be handy.
## Detect when a user specifies a relative/absolute path to --ignore-dir/--ignore-file

See also #291 and #330.
## Add --warnings/--no-warnings

If we're going to have warnings, we should probably have a way of turning them off.

**Comment by petdance** [comment]
There will probably be no more releases of ack 2.  If this is still a relevant idea, please submit it to the ack3 repo.
