### ISSUE TITLE
A short version for `--ignore-dir` option

### ISSUE THREAD

**Issue by chestozo** [beyondgrep/ack2#258]
Is it possible / will it be useful for other people to add some abbreviation for `--ignore-dir` option?
I use it a lot and it is a pain to add this option many times (because it is too long).

Is it possible to add a short version for it like `--xd`?

Issue started here:
https://github.com/petdance/ack/issues/145

**Comment by petdance** [comment]
There will probably be no more releases of ack 2.  If this is still a relevant idea, please submit it to the ack3 repo.
