### ISSUE TITLE
--ignore-dir doesn't support absolute pathnames

### ISSUE THREAD

**Issue by CapnKernel** [beyondgrep/ack2#291]
I'm trying out ack 2.04.  I have some subdirs that contain 1m+ files that I don't want ack to search.  --ignore-dir works if I give it relative dirs, but not with absolute pathnames.  For example, this finishes in 6 seconds:

  ack --ignore-dir={userimage,skins,catalog,detailed_image,var,var220,images} -w db_num_rows

But this is still going after 20 minutes:

  ack --ignore-dir=$PWD/{userimage,skins,catalog,detailed_image,var,var220,images} -w db_num_rows

It would seem that ack isn't smart enough to match up an absolute pathname to a relative pathname.

The reason I want to use absolute pathnames is that I may be somewhere "nearby", filesystem-wise, but I still want ack to ignore these dirs if a search would go into there.  And I want to put these ignorable dirs into the .ackrc file.

(It could also be me, in which case accept my apologies, but if so, this does seem to violate the Principle of Least Surprise)

**Comment by pmorch** [comment]
Yes please. Some way to exclude files based on paths, not just the last path element, would be a fantastic addition.
(Like e.g. the explicitly mentioned unsupported `foo/bar` from the man page)
