### ISSUE TITLE
Feature request: single-line files just report match or not, if they are big

### ISSUE THREAD

**Issue by hoelzro** [beyondgrep/ack2#345]
https://github.com/petdance/ack/issues/159

Various programs produce text files all on a single line. These files can be quite big. If you search them with ack and it finds a match, then it prints the whole file contents.

If a file has just a single line and that line is more than, say, 1000 characters long, then ack should suppress its normal printout of matching lines and just say 'Single-line text file X matches'.

**Comment by epa** [comment]
FWIW, there are quite a lot of tools which produce one-line text files by default.  Lots of XML data files are like that for example.  HTML can be too.

**Comment by pdl** [comment]
Not the same but similar use case: https://github.com/petdance/ack2/issues/366

**Comment by petdance** [comment]
We should organize all the "How do we handle long lines?" issues into one.  Probably it won't get done until ack3.
