### ISSUE TITLE
Should tags file be searched?

### ISSUE THREAD

**Issue by dionyziz** [beyondgrep/ack2#403]
Ctag files in the project root (a file called tags) is searched when using ack. Is this desired behavior? Usually when searching in source code we're not interested in this.

**Comment by worldmind** [comment]
Why ack did not ignore TAGS file by default?
Documentation says that ack it is grep for programmers and as I understood it's mean that ack has good default setting for developers?

**Comment by petdance** [comment]
I decided against it because it's entirely likely that folks could have a "tags" file somewhere in their tree that is not related to `ctags`.  Putting it in your project's `.ackrc` works fine.

**Comment by worldmind** [comment]
Sorry, i think about uppercase TAGS file, but after some thinking I undestood that it will not work on MS Windows systems.
