### ISSUE TITLE
Support optionally searching compressed files (RFE)

### ISSUE THREAD

**Issue by PhilHudson** [beyondgrep/ack2#406]
Emacs supports transparent access to gzip-compressed Emacs Lisp source code files. It essentially treats foo.el and foo.el.gz identically, dynamically and transparently compressing and decompressing as required for loading, editing, saving and compiling. No doubt other tools have similar functionality, or will have eventually.

Ack does not currently allow me to search .el.gz files along with .el files when I search a directory tree and I would dearly love it to.

I would suggest the following:
- Let {.abc,.xyz} be the set of valid file extensions supported by a given ack type-set 'myset'.
- In the presence of a type-add=myset:includecompressed:gz user option, transparently add {.abc.gz,.xyz.gz} to that set of valid file extensions.
- Search all valid files (_.abc,_.abc.gz,_.xyz,_.xyz.gz) within the specified directory tree, transparently expanding compressed ones.
- In the absence of gzip from the PATH, write something informative to stderr but don't abort. No change to ack exit statuses should result from implementing this RFE.
- Consider whether to support compressed formats other than gzip or whether YAGNI.

So I would add to my .ackrc:

--type-add=elisp:includecompressed:gz

...and ack would then transparently search all my elisp code as I want it to.

**Comment by petdance** [comment]
Added to https://github.com/petdance/ack2/wiki/Feature-requests
