### ISSUE TITLE
ack 2.12 about 10 times slower than grep 2.18  (Linux 64 bit)

### ISSUE THREAD

**Issue by kmansoft** [beyondgrep/ack2#465]
I just learned about ack, and absolutely love it (for file types, output format, and the ignore list).

However, it seems it's really not faster than grep: on my development system, it's about 10 times slower.

This is not really an issue for me, but I thought I'd mention it.

Environment: Fedora 20 + testing updates, 64 bit, kernel 3.14.4
Hardware: Intel i7 4770, 16 G RAM, SSD's
File system: ext4

ack version: 2.12 from distro repos
grep version: 2.18 from distro repos

Source file set: a subdirectory of [Android framework source code from the master branch](http://source.android.com/source/downloading.html).

`.../frameworks/base/core/java`

1895 files taking 28 megabytes (1400 of them Java)

I performed multiple runs to get the files into system memory caches, even though the disk drive is an SSD.

**grep, all files**

```
$ time grep -r getWidth . | wc
    305    2128   32201

real    0m0.060s
user    0m0.050s
sys 0m0.012s
```

**grep, Java files**

```
$ time grep  getWidth $(find . -name "*.java") | wc
    304    2125   32140

real    0m0.077s
user    0m0.069s
sys 0m0.010s
```

**ack config**

```
$ cat ~/.ackrc 
--ignore-directory=is:build
--ignore-directory=is:bin
--ignore-directory=is:gen
```

**ack, all files**

```
$ time ack  getWidth | wc
    305    2128   32908

real    0m0.614s
user    0m0.582s
sys 0m0.030s
```

**ack, Java files**

```
$ time ack  --java getWidth | wc
    304    2125   32846

real    0m0.584s
user    0m0.572s
sys 0m0.012s
```

Piping to wc or not produces slightly different numbers, but overall it's the same: ack is slower by about 10 times.

I also tried Ubuntu 14.04 64 bit on same hardware, with grep 2.16. The results are very close.

**Comment by petdance** [comment]
See also #610

**Comment by petdance** [comment]
There's work being done on optimization in ack 3.  I'm closing this old ticket as there will be no more ack 2 releases.
