### ISSUE TITLE
Neither the new bash and zsh completers nor the script to generate them are shipped in the CPAN tar ball

### ISSUE THREAD

**Issue by xtaran** [beyondgrep/ack2#486]
I tried to include the new completers (as mentioned in Changes) into ack's Debian package, but they're not in the 2.14 tar ball which I downloaded from CPAN, nor is `dev/generate-completion-scripts.pl` included. The make target to generate them is included, though:

```
/usr/bin/make completion.zsh completion.bash
make[2]: Entering directory '/home/abe/pkg-perl/git/packages/ack-grep'
./dev/generate-completion-scripts.pl completion.zsh
make[2]: ./dev/generate-completion-scripts.pl: Command not found
Makefile:1045: recipe for target 'completion.zsh' failed
make[2]: *** [completion.zsh] Error 127
make[2]: Leaving directory '/home/abe/pkg-perl/git/packages/ack-grep'
```

Please include either the generated completers or the script to generate them in the next release tar ball uploaded to CPAN.

**Comment by petdance** [comment]
Which files exactly should be included in the distro?
