### ISSUE TITLE
--ignore-dir still applies to a directory I explicitly specify on the command line

### ISSUE THREAD

**Issue by hoelzro** [beyondgrep/ack2#492]
For example:

```
$ ack --ignore-dir=nqp nqp/ -f
```

I expected it to continue searching the `nqp` subdirectory anyway, since I told it to, and ack seems to have a policy of "if you explicitly tell me what to search, I'll ignore my rules and search it".  The analogous command for a file works fine:

```
$ ack --ignore-file=is:INSTALL.txt INSTALL.txt -f
INSTALL.txt
```

**Comment by voidus** [comment]
This is really annoying

**Comment by petdance** [comment]
> ack seems to have a policy of "if you explicitly tell me what to search, I'll ignore my rules and search it".

Yes, that's intentional.

I'm sorry the --ignore-dir stuff is a mess. :-(

**Comment by voidus** [comment]
Don't be. It's just something that needs work :)
