### ISSUE TITLE
`ack --man` has invalid hyphens (`man ack` is fine)

### ISSUE THREAD

**Issue by OnlineCop** [beyondgrep/ack2#505]
As reported in https://groups.google.com/forum/#!topic/ack-users/1BaK7iyffzQ, typing `man ack` works fine and short- and long options display hyphens.  Typing `ack --man` outputs some character other than a hyphen (which limits searching for options with hyphens).
# 

uname -a
    Darwin MacBookPro.local 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64

ack --version
    ack 2.12
Running under Perl 5.16.3 at /opt/local/bin/perl5.16

​​perldoc -V​
    Perldoc v3.15_02, under perl v5.012005 for darwin

​perl -V
    Summary of my perl5 (revision 5 version 12 subversion 5) configuration:

  Platform:
    osname=darwin, osvers=13.1.0, archname=darwin-thread-multi-2level
    uname='darwin tennine-slave.macports.org 13.1.0 darwin kernel version 13.1.0: thu jan 16 19:40:37 pst 2014; root:xnu-2422.90.20~2release_x86_64 x86_64 '

**Comment by petdance** [comment]
When you say "Typing ack --man outputs some character other than a hyphen", where are you referring to in the output?  Where exactly in the output are you seeing not-a-hyphens where you expect hyphens?

**Comment by petdance** [comment]
This is addressed in ack 3.
