### ISSUE TITLE
Don't let ack take up all memory

### ISSUE THREAD

**Issue by hoelzro** [beyondgrep/ack2#514]
In some (fairly) recent changes to ack since 2.14, I created an optimization by reading in a file in its entirely and calling the regex engine on that giant blob instead of applying the regex line by line.  This is great, as it results in a giant speed boost.  What's not so great is when ack mistakenly starts searching a huge file that consumes all memory on the machine.  So there are a few ways we can get around this:
- Before ack starts searching a file, check its size.  If it's over some preset limit, fallback to line-by-line searching.
- Read a file in fixed size chunks (perhaps the same chunk size as stdio uses) and scan those.
- Use mmap (this could be the default, falling back to one of the other two if mmap isn't available)

**Comment by hoelzro** [comment]
For the mmap route, `Sys::Mmap` and `File::Map` seem to be popular choices.

**Comment by petdance** [comment]
There will probably be no more releases of ack 2.  If this is still a relevant idea, please submit it to the ack3 repo at https://github.com/beyondgrep/ack3.
