### ISSUE TITLE
XDG Base Directory Specification

### ISSUE THREAD

**Issue by sullyj3** [beyondgrep/ack2#516]
Is there any chance of xdg support for ackrc? I'd much prefer the config file under ~/.config/ack/config or ~/.config/ackrc than cluttering up my home directory.

**Comment by ZuBB** [comment]
Is priority of per-project .ackrc higher than value of ACKRC environment variable?

**Comment by hoelzro** [comment]
I believe ACKRC takes precedence

**Comment by hoelzro** [comment]
nope, I'm wrong; ACKRC overrides the location for your *user* ackrc,  so it comes after the project ackrc.

**Comment by ZuBB** [comment]
Is there any chance that you will change that behaviour?

**Comment by petdance** [comment]
Probably not.  It's been the way it is for years.

**Comment by ZuBB** [comment]
Ok, let me give an example

we set git opts globally (per user) in `~/.gitconfig`. However we can overwrite some opts for a particular project via `$PROJECT_HOME/.git/config`.

git searches its config in home dir. if nothing found, he also looks into `$HOME/.config/git/` (standart by X.org for all settings/rc files, ie XDG).

With help of ACKRC we are able to have "global" .ackrc in `.config`. but in that case it not possible override some things at project level

**Comment by hoelzro** [comment]
I thought that ACKRC just replaces the user ackrc; it doesn't stop ack from looking for project ackrcs.  So you can set `ACKRC=$HOME/.config/ackrc` and still retain your ability to make project-specific overrides.
