### ISSUE TITLE
ack is ambiguous about newlines at the end of the line

### ISSUE THREAD

**Issue by pdl** [beyondgrep/ack2#525]
Given:

```
package Foo;
use Moo;
has Goo => (
  is => 'rw',
);
has Too =>
  is => 'rw';
```

In the following case, line 6 is highlighted, line 3 is not. I didn't expect 3 to appear at all.

```
$ ack --perl "^has .*[^\(]$"
Foo.pm
3:has Goo => (
6:has Too =>
```

I can get what I want as follows (but I'd prefer not to have to add the `\n`)

```
$ ack --perl "^has .*[^\(\n]$"
Foo.pm
6:has Too =>
```

In this case, line 3 is highlighted:

```
$ ack --perl "^has .*\($"
Foo.pm
3:has Goo => (
```

In this case, it is not highlighted:

```
$ ack --perl "^has .*\(\n$"
Foo.pm
3:has Goo => (
```

Is this intentional?

I'm on ack 2.14 running under Perl 5.20.2 on 64-bit Fedora.

**Comment by petdance** [comment]
Is your question about what is matching, or what is getting highlighted?

**Comment by pdl** [comment]
My main concern is that the first case seems wrong - line 3 should not match `^has .*[^\(]$` at all in my view. The rest is just observation in an attempt to work out why ack is matching line 3.

**Comment by hoelzro** [comment]
I believe this is fixed as in Git HEAD:

![ack-525](https://cloud.githubusercontent.com/assets/107804/6337169/a9bbb18e-bb6d-11e4-93fe-db8096a0080d.png)

**Comment by pdl** [comment]
Ah, great - thanks!

**Comment by petdance** [comment]
This is the same as #522

**Comment by petdance** [comment]
@pdl: Did you try the version on HEAD and verify it's been fixed to your satisfaction?

**Comment by pdl** [comment]
@petdance I can reproduce @hoelzro's result, it's fixed on the current state of dev, i.e. c92cb6c.

**Comment by petdance** [comment]
This is fixed in ack3.  There will be no more releases of ack 2.
