### ISSUE TITLE
Pattern starting with a ^ (beginning of line) doesn't work when --files-with-matches option is used unless match is on first line

### ISSUE THREAD

**Issue by GordanV** [beyondgrep/ack2#538]
I have found that the a regex beginning with a caret that finds matches in a file doesn't list the files found when the `-l` / `--files-with-matches` option is used unless the match occurs in the first line.

Steps to reproduce:
1. Create testfile: `echo -n "Don't Match this line\n   but this one" > ack_testfile`
2. Find matches with ack: `ack --noenv '^\s+' ack_testfile`
    - Actual result: `but this one`
3. Find filenames containing matches: `ack --noenv -l '^\s+' ack_testfile`
    - Expected result: `ack_testfile`
    - Actual result is empty

If I search for "^Don't" the `-l` option works as expected.

It seems like the meaning of `^` changes from 'beginning of line' to 'beginning of file' when the the `-l` option is used.

This should either be mentioned in the man page (or maybe a warning should be displayed when using that option) or preferably ack should behave the same with and without those options (`-L` / `--files-without-matches` is also affected).

**Comment by hoelzro** [comment]
This *does* occur on 2.14, but is fixed in the dev branch.

**Comment by hoelzro** [comment]
I *do*, however, see this probably with `-L`!  Great catch!

**Comment by GordanV** [comment]
Great to hear and thanks for the quick reply!

**Comment by petdance** [comment]
This is good in ack 3.
