### ISSUE TITLE
suppress errors -s ineffective with -x file list on standard-input

### ISSUE THREAD

**Issue by n1vux** [beyondgrep/ack2#544]
There is  a bug in -x -s combination not suppressing messages, reproducible on other OS than reported Windows, eg Linux. :

```
    (ls *.txt; echo no-such-file.txt)| ack -xs -li panel
    launch-panel.txt
    ack: no-such-file.txt: No such file
```

(Indeed, the file about panels contains panel, and the other *.txt do not.)

And base case, 

```
ack -s -li panel no-such-file.txt
```

is properly silent.

( Per email report "-s option does not work" on ack-users re searching *.doc on Windows; don't do that, but -s is still broken. )

**Comment by petdance** [comment]
This has been fixed in ack 3.
