### ISSUE TITLE
Files from recursive file search should always be sorted

### ISSUE THREAD

**Issue by rillig** [beyondgrep/ack2#550]
When I run `ack return src`, the files from the `src` directory are listed in apparently random order. This order can be changed by passing the `--sort-files` option. But then, all files are sorted, no matter in which order they were given on the command line.
- When scanning a directory recursively for files, these files should always be sorted alphabetically.
- The option `--sort-files` should only affect the files that were given explicitly on the command line.

Example: When running `ack searchTerm /usr/include include src checks`, the files should be displayed in the following order:
1. all files from `/usr/include`, sorted alphabetically
2. all files from `include`, sorted alphabetically
3. all files from `src`, sorted alphabetically
4. all files from `checks`, sorted alphabetically

**Comment by hoelzro** [comment]
@rillig The way ack find files to search (regarding order, and ignoring things like filters) is this:

    Get list of files from current directory
    If --sort-files is on, sort that list in lexicographical order
    For each file in that list:
        If the file is a directory, recurse into it
        Otherwise, search its contents

I don't think @petdance will want to change this behavior, mainly since it would affect and surprise all of the users who understand ack to behave as specified above.

**Comment by petdance** [comment]
I don't know.  It's an interesting idea.  I can see why you'd want to specify a certain order for things on the command line.

**Comment by rillig** [comment]
To prevent a misunderstanding:

* Currently, when getting the list of files from a directory, the files are not sorted at all.
* I want the files from a single directory to be sorted alphabetically, since “filesystem read order” is mostly arbitrary and not useful.
* I don’t want any other behavior to be changed.

**Comment by petdance** [comment]
You can get the files sorted with `--sort-files`, but then you'll also get your starting directories sorted as well.

**Comment by epa** [comment]
Sorting the files is probably more useful than the current behaviour, but perhaps marginally slower (on rotating storage at least).  However it might not be good to commit to sorted filenames as documented behaviour, since it precludes optimizations like scanning the tiny files first and leaving huge ones for later.  I guess `--sort-files-within-directory` as an explicit option would work.
