### ISSUE TITLE
Please add inl as one of the cpp file extentions, by default

### ISSUE THREAD

**Issue by hefengrren** [beyondgrep/ack2#561]
"The INL file type is primarily associated with 'Visual C++' by Microsoft Corporation."
-- Quoted from: http://filext.com/file-extension/INL.

**Comment by petdance** [comment]
Have you added it to your local .ackrc file?

**Comment by hefengrren** [comment]
No.
Actually, I prefer stick to the default, instead of customize my own and sync between machines.

And, there seems no heavy use of INL extension for other purposes.
So, I guess it is a good candidate to be defaulted.

**Comment by petdance** [comment]
There will probably be no more releases of ack 2.  If this is still a relevant idea, please submit it to the ack3 repo.
