### ISSUE TITLE
ack '^\s+$' finds more hits than it should

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack2#562]
I went searching for lines that were all whitespace, so I did

```
ack '^\s+$'
```

This found some lines in files that were all whitespace, and highlighted the whitespace correctly, but it also seemed to find lines that had no whitespace, but were followed immediately by other blank lines.

**Comment by hoelzro** [comment]
I just encountered this myself.

**Comment by hoelzro** [comment]
I'm 99% sure that this is due the optimization I added in e3a5b3c.

**Comment by karenetheridge** [comment]
I also just ran into a case where `ack ' $'` returned results, but `ack -l ' $'` returned nothing.

**Comment by xtaran** [comment]
Hi Karen,

On Wed, Jul 22, 2015 at 10:20:08AM -0700, Karen Etheridge wrote:
> I also just ran into a case where `ack ' $'` returned results, but `ack -l ' $'` returned nothing.

That's a different bug, either #491
(https://github.com/petdance/ack2/issues/491) or #498
(https://github.com/petdance/ack2/issues/498).

			Regards, Axel

**Comment by openstrike** [comment]
Hello. I've been assigned ack2 as part of the [CPAN PR Challenge](http://cpan-prc.org/). If nobody objects, I'd like to take a crack at fixing this issue.

**Comment by openstrike** [comment]
After looking at the detail of the code I agree with @hoelzro. The action of slurping in the whole file into a scalar and then trying to match with the caret and dollar causes problems when the regex can match \n. eg:

```
   perl -e '"\n\n\n\n" =~ /^\D+$/m; print "x$&x\n";'
```

Having thought about this a little I cannot spot any clean way around it. Any post-processing which could be done after the match is already too late AFAICS. Coversely, pre-processing the regex seems hackish and would be difficult to implement given the number of possible ways a regex might match \n. The only solution I can see involves splitting the content into lines first and that would negate the purpose of this section of code in the first place (optimisation).

Any other suggestions?

**Comment by petdance** [comment]
How tough is it to reverse the optimization?  Accuracy trumps speed.

**Comment by hoelzro** [comment]
@petdance I don't think it'd be too hard, but I'd rather figure out a way to keep the optimization, as it speeds up the common case quite a bit.

**Comment by petdance** [comment]
How much is quite a bit?

**Comment by hoelzro** [comment]
[git:(HEAD detached at e3a5b3c)] [10:13:31] rob@lepus ~/projects/ack2 $ perl dev/timings.pl --ack=HEAD --color --times=5        
                                        | previous |   HEAD
    -------------------------------------------------------------------------
               ack foo /home/rob/parrot |   0.76 |   0.60
          ack foo --cc /home/rob/parrot |   0.40 |   0.35
        ack foo --rust /home/rob/parrot |   0.32 |   0.30
       ack foo --known /home/rob/parrot |   0.73 |   0.56
                ack -f /home/rob/parrot |   0.40 |   0.40
           ack -f --cc /home/rob/parrot |   0.36 |   0.31
         ack -f --rust /home/rob/parrot |   0.35 |   0.31
        ack -f --known /home/rob/parrot |   0.41 |   0.37
            ack foo -l /home/rob/parrot |   0.49 |   0.47
       ack foo -l --cc /home/rob/parrot |   0.34 |   0.32
     ack foo -l --rust /home/rob/parrot |   0.32 |   0.30
    ack foo -l --known /home/rob/parrot |   0.48 |   0.47
            ack foo -c /home/rob/parrot |   0.53 |   0.48
       ack foo -c --cc /home/rob/parrot |   0.33 |   0.34
     ack foo -c --rust /home/rob/parrot |   0.31 |   0.31
    ack foo -c --known /home/rob/parrot |   0.49 |   0.48

Something like 20% faster, it seems.

**Comment by hoelzro** [comment]
This should now be resolved.

**Comment by karenetheridge** [comment]
I don't see a recent release -- is there a certain commit or version tag I should be watching?

**Comment by petdance** [comment]
It will be 2.15_02 when I put it out.
