### ISSUE TITLE
--context and files with carriage returns

### ISSUE THREAD

**Issue by epa** [beyondgrep/ack2#597]
If a file contains carriage returns but you are running on a Unix-like system, then `ack --context` can print its results in such a way that some lines become invisible.

```
% mkdir test
% cd test
% perl -E 'print "hello\r\n" foreach 1, 2' >out
% ack --context=1 hello
out
1:hello

% ack hello out
1:hello
2:hello
```

Observe that when `--context` is given, only the first match is visible on screen.

**Comment by petdance** [comment]
What does `grep` do in such a case?

**Comment by epa** [comment]
`grep` prints both lines.  I think this is something to do with `--color`.

**Comment by petdance** [comment]
We redid how colorzing works in ack 3.  This works in ack 3.  There will be no more releases of ack 2.
