### ISSUE TITLE
Addition of .ipp as a supported file type under cpp

### ISSUE THREAD

**Issue by kojik1010** [beyondgrep/ack2#598]
Originally posted in https://groups.google.com/forum/#!topic/ack-users/ya-8rBCun0E

Reposting here as requested by @petdance 

> Hi
> 
> I have not seen ipp files elsewhere, but Boost libraries puts implementation of templated code in ipp files instead of in cpp files ( http://lists.boost.org/Archives/boost/2003/08/51197.php ). I have defined it in my .ackrc file but since Boost contains many widely used C++ libraries, I am proposing supporting ipp files under cpp group by default.
> 
> Thanks!

**Comment by petdance** [comment]
ack 2 has no more planned releases.   If this is still important, please submit as an issue in the ack3 project.
