### ISSUE TITLE
Add support to Wolfram file formats

### ISSUE THREAD

**Issue by lumeng** [beyondgrep/ack2#620]
I'd like to add support to the file types used in Wolfram Language/Mathematica:

* Wolfram notebook files (*.nb):
  - http://www.wolfram.com/technologies/nb/

* Wolfram CDF files (*.cdf):
   - http://www.wolfram.com/cdf/index.html

* Wolfram Language/Mathematica package files (*.m, *.wl):
  - https://reference.wolfram.com/language/tutorial/WolframLanguagePackages.html
  - http://reference.wolfram.com/language/tutorial/WolframLanguageScripts.html

* Wolfram Language/Mathematica  test files (*.mt, *.wlt):
  - https://reference.wolfram.com/language/tutorial/UsingTheTestingFramework.html

I've opened a pull request: https://github.com/petdance/ack2/pull/618/files

**Comment by petdance** [comment]
I'm wary of adding this because I don't know how widespread these are.

Have you been using these in your .ackrc?  How long?
