### ISSUE TITLE
Add kotlin support

### ISSUE THREAD

**Issue by nwolff** [beyondgrep/ack2#621]
filename extensions are .kt and .kts : https://en.wikipedia.org/wiki/Kotlin_(programming_language)

I'm able to search in kotlin files by adding 

```
--type-add=kotlin=.kt,.kts
```

to ```.ackrc```

It would be nice if the type was there by default in ack.

I'll create a pull request if you give me the greenlight for this.

**Comment by petdance** [comment]
I'd like to hear from anyone else using Kotlin.  Isn't it a pretty new language?

**Comment by gimlet2** [comment]
@petdance Kotlin is growing pretty fast - on Android and as general replacement of Java. For example we have several services in production. Please add Kotlin type!

**Comment by vanniktech** [comment]
@petdance can we please add this? Especially giving that Android now fully supports Kotlin as a first party language.

**Comment by petdance** [comment]
Are those the only two rules?  Kt and kts?  Does it run from shell and we need to add a shebang?  Any other special rules like how Rakefile is another Ruby file?

**Comment by petdance** [comment]
Added in 54026a3.  Will be in 2.21_01.

**Comment by petdance** [comment]
Added in 54026a3. Will be in 2.21_01.

**Comment by vanniktech** [comment]
This should be enough. Thanks for adding it :)
