### ISSUE TITLE
When part of CWD is a symlink, .ackrc is searched moving up the real path instead of the symlinked path

### ISSUE THREAD

**Issue by Tomaz-Vieira** [beyondgrep/ack2#637]
- I have a jail that contains a build environment that I use.
- This jail has its own .ackrc in the jailUser home dir
(`/home/hostUser/rootfs/jessierootfs/home/jailUser/.ackrc` as seen by the host or
`/home/jailUser/.ackrc` as seen from within the jail)
- My host filesystem also has a .ackrc in the hostUser home dir
(`/home/hostUser/.ackrc`)
- I created a symlink from my host filesystem into the jail filesytem and `cd` into it
`ln -s /home/hostUser/rootfs/jessierootfs/home/jailUser/jailCode /home/hostUser/jailCode`
`cd  /home/hostUser/jailCode`
- Now whenever I try ack-ing within this symlink into the jail, I get error messages which contain
`ack: Invalid option in /home/hostUser/rootfs/jessierootfs/home/jailUser/.ackrc`
that is, the jailUser's .ackrc is seen as a project .ackrc

I'm not quite sure if this is a bug, as It'd make sense to use the project .ackrc when using a symlink in a project's subdir, but it is rather confusing to see the CWD in the shell prompt and have an .ackrc file 'outside' that path being used by ack.

**Comment by petdance** [comment]
There will be no more releases of ack 2.  If this is still an issue in ack 3, please create a ticket there: https://github.com/beyondgrep/ack3
