### ISSUE TITLE
Make test is failing

### ISSUE THREAD

**Issue by PezCoder** [beyondgrep/ack2#648]
### What ?
I'm following the instructions specified in this repository to install ack2 i.e
```shell
# Required
perl Makefile.PL
make
make test
sudo make install # for a system-wide installation (recommended)
```

### Machine info
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

perl 5, version 18, subversion 2 (v5.18.2)

### Output for `make test` command
[Output logs](https://github.com/beyondgrep/ack2/files/1288703/x.txt)

I'm assuming that the test has to pass for me to continue with `sudo make install` i actually tried it with failing tests & it broke everything.

###  Help 🙏🏽

**Comment by petdance** [comment]
Is File::Next installed?  What is the output from `perl Makefile.PL`?

**Comment by PezCoder** [comment]
1. Is File::Next a dependency for ack2, i'll check if so.
2. output for `perl Makefile.PL`
```
Warning: prerequisite File::Next 1.16 not found. We have 1.12.
Writing Makefile for ack
Writing MYMETA.yml and MYMETA.json
```

**Comment by petdance** [comment]
> Is File::Next a dependency for ack2, i'll check if so.

That's what this error is saying.

    Warning: prerequisite File::Next 1.16 not found. We have 1.12.

**Comment by PezCoder** [comment]
Yeah, I'll upgrade it & check, Thanks.

**Comment by petdance** [comment]
Makefile.PL is a little weird.  You have to read the output from it.  Even though it makes a makefile, and therefore you're able to run `make test`, that doesn't mean that everything is OK.

**Comment by PezCoder** [comment]
Thanks for the quick response @petdance After installing your [File::Next](https://github.com/petdance/file-next) package it went smoothly.
