### ISSUE TITLE
ack should also ignore .git files

### ISSUE THREAD

**Issue by micampe** [beyondgrep/ack2#653]
When using git submodules `.git` will be a file instead of a directory, I added `--ignore-file=is:.git` to my `.ackrc`.

**Comment by petdance** [comment]
Are there others we should address?  Looks like directory `.gitmodules` would be one, too.  https://git-scm.com/docs/gitmodules

**Comment by petdance** [comment]
Thanks.  Added to 26a40ca.  It will be released in 2.19_01.
