### ISSUE TITLE
Can't locate File/Next.pm in @INC (you may need to install the File::Next module)

### ISSUE THREAD

**Issue by yuchao86** [beyondgrep/ack2#666]
```
yuchao@localhost: ~/Github/ack2 dev
 $ ls                                                                [17:05:11]
Ack.pm            ExtensionGroup.pm MYMETA.yml        dev
CONTRIBUTING.md   Filter.pm         Makefile          garage
Changes           FirstLineMatch.pm Makefile.PL       perlcriticrc
Collection.pm     Inverse.pm        Match.pm          perltidyrc
ConfigDefault.pm  Is.pm             MatchGroup.pm     pm_to_blib
ConfigFinder.pm   IsGroup.pm        README.md         record-options
ConfigLoader.pm   IsPath.pm         Resource.pm       squash
DESIGN.md         IsPathGroup.pm    Resources.pm      t
DEVELOPERS.md     LICENSE.md        ack               tack
Default.pm        MANIFEST          ack-standalone    test-pager
Extension.pm      MYMETA.json       blib              xt

yuchao@localhost: ~/Github/ack2 dev
 $ ./ack                                                             [17:06:22]
Can't locate File/Next.pm in @INC (you may need to install the File::Next module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2/darwin-thread-multi-2level /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at ./ack line 12.
BEGIN failed--compilation aborted at ./ack line 12.
FAIL
```

**Comment by petdance** [comment]
Have you done anything to install ack?  Or did you just check out the repository?

If you want to install ack, you need to use the standard method for installing Perl modules/programs:

    perl Makefile.PL
    make
    make test
    sudo make install

**Comment by petdance** [comment]
Have you done anything to install ack? Or did you just check out the repository?

The instructions for installing ack are in the `README.md` file.

**Comment by yuchao86** [comment]
I used the fellow command to build this ack2, but still error..

ack requires Perl 5.8.8 or higher. Perl 5.8.8 was released January 2006.

# Required
perl Makefile.PL
make
make test
sudo make install # for a system-wide installation (recommended)


I used the mac OS High Sierra 10.13.4...

**Comment by petdance** [comment]
You need to install File::Next before you can install ack.  Alternatively, you can download the single-file download of ack at https://beyondgrep.com/install/

**Comment by djangohunt** [comment]
I am also getting this issue, ack and File::Next are both installed

**Comment by petdance** [comment]
@djangohunt This repo is for ack 2 that is no longer supported.  Are you using ack 2 or 3?  If 2, please try with 3.  If that doesn't work, please open a new ticket over at https://github.com/beyondgrep/ack3 and give details of what you've done and your install process etc.

Thanks.
