### ISSUE TITLE
Fix documentation for --lines

### ISSUE THREAD

**Issue by hoelzro** [beyondgrep/ack2#673]
See https://github.com/beyondgrep/ack3/issues/166

The documentation for `--lines` currently says:

```
  --lines=NUM                   Only print line(s) NUM of each file.  No
                                pattern is matched.
```

`--lines=NUM` implies only a single number may be specified, but `line(s) NUM` implies one may supply several.  Not only is this inconsistent, but it doesn't explain _how_ one would specify multiple lines if they desired.

For reference, you can specify a comma-separated list of expressions, each of which is a single integer line number, or a dash-separated `start-end` range, which matches all lines between `start` and `end`, inclusive.

**Comment by petdance** [comment]
Updated in 2.26.
