### ISSUE TITLE
Weird behaviour not ignoring files and searching non-files?

### ISSUE THREAD

**Issue by ryanmortier** [beyondgrep/ack2#675]
![image](https://user-images.githubusercontent.com/2053960/48211849-636c6a00-e348-11e8-9bef-b2ad4015b1f3.png)

![image](https://user-images.githubusercontent.com/2053960/48212029-c4943d80-e348-11e8-83bd-bbdd8fbee80b.png)

![image](https://user-images.githubusercontent.com/2053960/48212051-d07fff80-e348-11e8-971a-32b00f18aa1d.png)

![image](https://user-images.githubusercontent.com/2053960/48212066-da096780-e348-11e8-808a-b56965720c92.png)

![image](https://user-images.githubusercontent.com/2053960/48212088-e261a280-e348-11e8-8d15-b79a62491568.png)

`ack` seems to be ignoring my ignored files but that isn't the worst part. The worst part is it keeps finding things in these weird non-files called `path`, `confirmation_`, `confirmation_path`, etc.

**Comment by petdance** [comment]
The `--ignore-files` doesn't use shell globbing.  You'll have to do `--ignore-file=node_modules` and `--ignore-file=vendor`.

**Comment by petdance** [comment]
The most correct way to do it would be `--ignore-dir=is:node_modules` and `--ignore-dir=is:vendor`.

**Comment by ryanmortier** [comment]
Solved. Yikes, actually the issue was pretty simple.

Turns out I had issued an `ack ->confirmation_path` command earlier (working with PHP objects) and trying to find string literal `->confirmation_path`.

Unknowingly this had dumped acks output to a file named `confirmation_path` including the composer.lock content.

Stupid mistake.

**Comment by petdance** [comment]
Glad you found it.  I've done that more than a few times myself.  I try to have the habit of looking for `-.method_name`.  Theoretically it could match `-Xmethod_name`, but I use it for safety if I'm just snooping around a codebase.
