### ISSUE TITLE
-s option has no effect when -x option is used

### ISSUE THREAD

**Issue by kawing-chiu** [beyondgrep/ack2#676]
I'm using ack 2.24. According to the doc, `-s` should suppress error messages about nonexistent files etc. However, when file list is read from stdin, it does not work:
```
$ ack -s some_pattern not_exist
$ echo not_exist | ack -s -x some_pattern
ack: not_exist: No such file
```

**Comment by petdance** [comment]
I'll fix it in ack itself.  I don't think it will be that big of a deal.

While I have your attention, can you tell me more about how you're using `-x`?  I rarely see people mention it, and it's one of my favorite features.  Did you just stumble across it in the docs and think "Hey, that's handy"?

**Comment by petdance** [comment]
This has been fixed in ack3.  There will be no more releases of ack 2.
